name: dl-graph-cpu
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - tqdm
  - pyyaml
  - pip:
    - -f https://data.pyg.org/whl/torch-2.6.0+cpu.html
    - torch==2.6
    - torchvision==0.21
    - torchaudio==2.6
    - torchmetrics==1.7
    - torch-geometric
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - pygod
