name: dl-graph-gpu
channels:
  - conda-forge
dependencies:
  - cuda-toolkit=12.4
  - cudnn
  - ipykernel
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.10
  - scipy
  - seaborn
  - tqdm
  - pyyaml
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - -f https://data.pyg.org/whl/torch-2.6.0+cu124.html
    - torch==2.6.0+cu124
    - torchvision==0.21.0+cu124
    - torchaudio==2.6.0+cu124
    - torchmetrics==1.7.0
    - pyg-lib==0.4.0+pt26cu124
    - torch-geometric==2.6.1
    - torch-scatter==2.1.2+pt26cu124
    - torch-sparse==0.6.18+pt26cu124
    - torch-cluster==1.6.3+pt26cu124
    - torch-spline-conv==1.2.2+pt26cu124
    - pygod==1.1.0

